# Generated by Django 5.0 on 2023-12-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripeapp', '0003_discount_tax_order_discount_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
