# Generated by Django 5.0 on 2023-12-23 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripeapp', '0004_order_client_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_secret',
        ),
        migrations.AddField(
            model_name='order',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stripeapp.clientsecret'),
        ),
    ]
